version: '3'
services:
  gb:
    build: .
    volumes:
    - ./public:/var/www/html
    - ./extra/apache.conf:/etc/apache2/sites-available/000-default.conf
    - ./extra/config.php:/var/www/html/application/config.php
    ports:
    - 8080:80
    depends_on:
    - db
  db:
    image: mariadb:5.5
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bg
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db_data: {}